### ISSUE TITLE
Making our page Alive!!

### ISSUE THREAD

**Issue by ExcViral** [geekyJock8/festWebsite#1]
We need to use Github's pages to see our changes live, as a website. So'i've cloned the repository to github pages. Now, Do one thing, access the repo settings, and go to branches, change the default branch from master to gh pages, and update.

**Comment by geekyJock8** [comment]
Should we go by my username or try creating an organization ?

**Comment by ExcViral** [comment]
let'm ake something worthy first :smile: then we'll change the url too!

**Comment by geekyJock8** [comment]
"We need to use Github's pages to see our changes live, as a website. So'i've cloned the repository to github pages. Now, Do one thing, access the repo settings, and go to branches, change the default branch from master to gh pages, and update."

I did what you asked but what was its purpose ?

**Comment by ExcViral** [comment]
sahi kiya... now as we commit changes, it will directly be saved for github pages. gh-pages was a command to copy our master repo to the github pages.(I guess so.) Now as we made the default branch as gh-pages, all changes will be saved in this branch by default, not in master branch

**Comment by ExcViral** [comment]
I saw IITD tryst website... they've use HTML5 Canvas for effects... site is very simple(after excluding canvas). so now let's discuss our basic layout. I mean what will be sections  of the site and all other stuff...

**Comment by ExcViral** [comment]
Also i can't find the version control... i mean every big changes we make has to be saved as a new file or new folder something... how do we get that working?

**Comment by geekyJock8** [comment]
to see previous versions check out the commits section each commit tells you the changes you made in that commit, in this way we can do version control. Also i guess we can divide our site into HOME, EVENTS, SPONSORS, CONTACT US, ABOUT US, SCHEDULE , FAQ

**Comment by ExcViral** [comment]
ohk... lets first make these labels
